version: '3'

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    network_mode: host
    volumes:
      - /var/app/current/alloy/config.alloy:/etc/alloy/config.alloy:ro
    environment:
      - ALLOY_ENV=${SPRING_PROFILES_ACTIVE}
      - SERVER_NAME=${SERVER_NAME}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
