version: '3'

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./var/app/current/alloy/config.alloy:/etc/alloy/config.alloy:ro
    environment:
      - ALLOY_ENV=prod
      - SERVER_NAME=prod-server
