spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none

  s3:
    input-bucket: ${INPUT_BUCKET_NAME}
    output-bucket: ${OUTPUT_BUCKET_NAME}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  header: "Authorization"
  prefix: "Bearer"
  issuer: "ddingdong"
  secret: ${JWT_SECRET}
  expiration: 3600

cloud:
  aws:
    ses:
      sender-email: ${SENDER_EMAIL}
    region:
      static: ${AWS_DEFAULT_REGION}
    stack:
      auto: false

swagger:
  server:
    url: ${SERVER_URL:http://localhost:8080}

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter : method
    doc-expansion : none

security:
  actuator:
    base-path: ${ACTUATOR_ALLOWANCE_SECURITY_PATH:/default}
