insert into users(name, password, role, userid)
values ('ddingdong', '$2a$12$9BIi3IGc79rU3Xgbnxq/X.T37Hlfrf/lSc2/g0HLeM1g7HmFXE8v.', 'ADMIN', 'ddingdong11'),
       ('cow', '$2a$12$9BIi3IGc79rU3Xgbnxq/X.T37Hlfrf/lSc2/g0HLeM1g7HmFXE8v.', 'CLUB', 'cow11');

INSERT INTO club(name,
                 category,
                 leader,
                 tag,
                 score,
                 phone_number,
                 location,
                 user_id,
                 start_recruit_period,
                 end_recruit_period,
                 regular_meeting,
                 introduction,
                 activity,
                 ideal,
                 form_url,
                 profile_image_url,
                 introduction_image_url)
VALUES ('카우',
        '학술',
        '김세빈',
        'IT',
        0,
        '010-0000-0000',
        'S1350',
        2,
        NULL,
        NULL,
        '매주 월요일 18:00시',
        '동아리 소개입니다.',
        '동아리 활동내용입니다.',
        NULL,
        NULL,
        NULL,
        NULL
       );
